config/routes.rb
Crewservicer::Application.routes.draw do
  root to: 'dashboard#index', as: :dashboard

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login/redirect' => 'sessions#create', as: :oauth_redirect
  get 'login/callback' => 'sessions#callback', as: :oauth_callback

  get 'mat' => 'dashboard#food_services', as: :food_services
  get 'meddelanden' => 'dashboard#messages', as: :messages, constraints: { format: 'atom' }

  get 'slideshow' => 'dashboard#info_slideshow', as: :slideshow
  get 'slideshow/messages' => 'dashboard#slideshow_messages', as: :slideshow_messages, constraints: { format: 'json' }

  scope path_names: { :new => "ny", :edit => "redigera" } do
    namespace :admin do
      resources :people, only: [ :index, :show, :update ], path: 'folk' do
        member do
          post 'pick_up_t_shirt', path: 'hamta-t-shirt'
          post 'check_in', path: 'checka-in'
        end

        collection do
          get 'search', path: 'sok'
        end
      end

      resources :events, only: [ :index ], path: 'event' do
        collection do
          post 'import', path: 'importera'
        end
      end

      resources :food_services, except: [ :edit ], path: "maltider"

      resources :radio_orders, path: 'radiobestallningar' do
        member do
          get 'delivery_note', path: 'foljesedel'
          get 'equipment_pickup', path: 'lamna-ut'
          post 'pickup_equipment', path: 'lamna-ut'
          get 'equipment_return', path: 'lamna-tillbaka'
          post 'return_equipment', path: 'lamna-tillbaka'
        end

        resources :radio_loans, only: [ :show ], path: 'radios' do
          member do
            post 'bind_radio', path: 'koppla-radio'
          end
        end
      end

      resources :radios, only: [ :index ]

      resources :t_shirt_orders, only: [ :index ], path: 't-shirts'

      resources :messages, except: [ :edit ], path: "meddelanden" do
        collection do
          post 'sort', path: 'sortera'
        end

        member do
          post 'publish', path: 'publicera'
          post 'restore', path: 'aterstall'
        end
      end
    end
  end

  get '404' => 'errors#not_found'
  get '422' => 'errors#change_rejected'
  get '500' => 'errors#server_error'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :require_authentication, except: [ :messages ]

  def index
    @upcoming_food_services = @current_event.food_services.upcoming.order('opens_at ASC').includes(:dishes).limit(2)
    @food_services_pending = @upcoming_food_services.empty? && @current_event.food_services.empty?
    @messages = Message.published.on_site.order('sort_priority ASC, published_at DESC')
  end

  def food_services
    @upcoming_food_services = @current_event.food_services.upcoming.order('opens_at ASC').includes(:dishes)
    @past_food_services = @current_event.food_services.past.order('opens_at DESC').includes(:dishes)
    @food_services_pending = @upcoming_food_services.empty? && @current_event.food_services.empty?
  end

  def messages
    @messages = Message.published.on_site.order('published_at DESC')

    respond_to do |format|
      format.atom { render layout: false }
    end
  end

  def info_slideshow
    render layout: false
  end

  def slideshow_messages
    @next_food_service = @current_event.food_services.upcoming.order('opens_at ASC').includes(:dishes).first
    @messages = Message.published.on_info_screen.order('sort_priority ASC, published_at DESC')

    respond_to do |format|
      format.json { render layout: false }
    end
  end
end

app/views/dashboard/_food_service.html.erb
<article class="food-service">
  <% if food_service.open? %>
    <header class="time-header open">
      <p>Nu! – <%= distance_of_time_in_hours_and_minutes_to_now(food_service.closes_at) %> kvar</p>
    </header>
  <% else %>
    <header class="time-header normal">
      <p>
          <%= human_relatable_time(food_service.opens_at) %>
          <% if food_service.opens_at > Time.now && food_service.opens_at <= (Time.now + 24.hours) %>
            – <%= distance_of_time_in_hours_and_minutes_to_now(food_service.opens_at) %>
          <% end %>
      </p>
    </header>
  <% end %>
  <ul class="dishes">
    <% food_service.dishes.each do |dish| %>
      <li>
        <span class="description"><%= dish.description %></span><br>
        <% if dish.vegetarian? %>
          <span class="detail"><span class="icon inline green">&#127810;</span> Vegetarisk</span>
        <% end %>
        <% if dish.lactose_free? %>
          <span class="detail"><span class="icon inline">&#10003;</span> Laktosfri</span>
        <% end %>
        <% if dish.gluten_free? %>
          <span class="detail"><span class="icon inline">&#10003;</span> Glutenfri</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</article>

app/views/dashboard/food_services.html.erb
<header>
  <h1>
    Matsedel
    <em><%= @current_event.name %></em>
  </h1>
</header>

<p class="back-to-dashboard"><a href="<%= dashboard_path %>">Tillbaka till alla meddelanden</a></p>

<% if @upcoming_food_services.size > 0 %>
  <% @upcoming_food_services.each do |food_service| %>
    <section class="content">
      <%= render 'food_service', food_service: food_service %>
    </section>
  <% end %>
<% else %>
  <section class="content">
    <% if @food_services_pending %>
      <p>Matsedeln kommer upp inom kort.</p>
    <% else %>
      <p>Inga fler måltider detta event.</p>
    <% end %>
  </section>
<% end %>

<% if @past_food_services.size > 0 %>
  <h2>Tidigare måltider</h2>
  <% @past_food_services.each do |food_service| %>
    <section class="content">
      <%= render 'food_service', food_service: food_service %>
    </section>
  <% end %>
<% end %>

app/views/dashboard/index.html.erb
<header>
  <h1>
    Crewinfo
    <em><%= @current_event.name %></em>
  </h1>
</header>

<% @messages.each do |message| %>
<section class="content">
  <div class="message">
    <h2><%= message.headline %></h2>
    <%= simple_format message.text %>
  </div>
</section>
<% end %>


<section class="content">
  <h2>Kommande måltider</h2>
  <% if @upcoming_food_services.size > 0 %>
    <div class="content-columns">
      <% @upcoming_food_services.each do |food_service| %>
        <div class="column half-width">
          <%= render 'food_service', food_service: food_service %>
        </div>
      <% end %>
    </div>
  <% else %>
    <% if @food_services_pending %>
      <p>Matsedeln kommer upp inom kort.</p>
    <% else %>
      <p>Inga fler måltider detta event.</p>
    <% end %>
  <% end %>
  <p><a class="button" href="<%= food_services_path %>">Hela matsedeln</a></p>
</section>

app/views/dashboard/info_slideshow.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0">
    <%= stylesheet_link_tag 'slideshow', :media => 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= javascript_include_tag 'slideshow' %>
    <script type="text/javascript">
      window.addEvent("domready", function() {
        new Slideshow(10000, "<%= slideshow_messages_url format: :json %>");
      });
    </script>
  </body>
</html>

app/views/dashboard/slideshow_messages.json.erb
[
  <% @messages.each_with_index do |message, i| %>
    {
      "headline": <%=raw message.headline.to_json %>,
      "text": <%=raw simple_format(message.text).to_json %>
    }<% unless i + 1 == @messages.length %>,<% end %>
  <% end %>
]