config/routes.rb
Crewservicer::Application.routes.draw do
  root to: 'dashboard#index', as: :dashboard

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login/redirect' => 'sessions#create', as: :oauth_redirect
  get 'login/callback' => 'sessions#callback', as: :oauth_callback

  get 'mat' => 'dashboard#food_services', as: :food_services
  get 'meddelanden' => 'dashboard#messages', as: :messages, constraints: { format: 'atom' }

  get 'slideshow' => 'dashboard#info_slideshow', as: :slideshow
  get 'slideshow/messages' => 'dashboard#slideshow_messages', as: :slideshow_messages, constraints: { format: 'json' }

  scope path_names: { :new => "ny", :edit => "redigera" } do
    namespace :admin do
      resources :people, only: [ :index, :show, :update ], path: 'folk' do
        member do
          post 'pick_up_t_shirt', path: 'hamta-t-shirt'
          post 'check_in', path: 'checka-in'
        end

        collection do
          get 'search', path: 'sok'
        end
      end

      resources :events, only: [ :index ], path: 'event' do
        collection do
          post 'import', path: 'importera'
        end
      end

      resources :food_services, except: [ :edit ], path: "maltider"

      resources :radio_orders, path: 'radiobestallningar' do
        member do
          get 'delivery_note', path: 'foljesedel'
          get 'equipment_pickup', path: 'lamna-ut'
          post 'pickup_equipment', path: 'lamna-ut'
          get 'equipment_return', path: 'lamna-tillbaka'
          post 'return_equipment', path: 'lamna-tillbaka'
        end

        resources :radio_loans, only: [ :show ], path: 'radios' do
          member do
            post 'bind_radio', path: 'koppla-radio'
          end
        end
      end

      resources :radios, only: [ :index ]

      resources :t_shirt_orders, only: [ :index ], path: 't-shirts'

      resources :messages, except: [ :edit ], path: "meddelanden" do
        collection do
          post 'sort', path: 'sortera'
        end

        member do
          post 'publish', path: 'publicera'
          post 'restore', path: 'aterstall'
        end
      end
    end
  end

  get '404' => 'errors#not_found'
  get '422' => 'errors#change_rejected'
  get '500' => 'errors#server_error'
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :t_shirt_orders

  validates_numericality_of :cco_id
  validates_presence_of :username
  validates_inclusion_of :administrator, in: [ true, false ]

  after_initialize :set_defaults

  def self.find_or_update_by_cco_user(cco_user)
    person = Person.find_or_initialize_by_cco_id(cco_user.uid)

    person.username = cco_user.username

    person
  end

  def to_param
    cco_id.to_s
  end

  def set_defaults
    self.administrator = false if administrator.nil?
  end
end

app/controllers/admin/people_controller.rb
require 'upc_code'

class Admin::PeopleController < ApplicationController
  before_filter :require_administrator_privileges
  before_filter :set_query, only: :search
  before_filter :set_cco_user, only: [ :show, :update ]

  def index
    @people = Person.order('administrator DESC, username ASC')
  end

  def show
    @event_info = CrewCorner::EventInfo.find(params[:id], @current_event.cco_id, access_token: @cco_access_token)
    @person = Person.find_or_update_by_cco_user(@cco_user)
    @t_shirt_orders = @person.t_shirt_orders.where(event: @current_event)
  end

  def pick_up_t_shirt
    @t_shirt_order = TShirtOrder.find(params[:t_shirt_order_id])
    @t_shirt_order.picked_up_at = Time.now
    @t_shirt_order.save

    redirect_to action: :show
  end

  def check_in
    @event_info = CrewCorner::EventInfo.check_in(params[:id], @current_event.cco_id, access_token: @cco_access_token)

    redirect_to action: :show
  end

  def update
    @person = Person.find_or_update_by_cco_user(@cco_user)
    @person.update_attributes(person_params)

    if @person.save
      redirect_to admin_person_path(@person)
    else
      @event_info = CrewCorner::EventInfo.find(params[:id], @current_event.cco_id, access_token: @cco_access_token)
      render action: :show
    end
  end

  def search
    case @query
    when Integer
      user = CrewCorner::User.find(@query, access_token: @cco_access_token)

      unless user.nil?
        redirect_to action: :show, id: @query
      else
        @users = []
      end
    when String
      @users = CrewCorner::User.search(@query, access_token: @cco_access_token)
    end
  end

  private

  def set_query
    @query = params[:q]
    @query = (@query.length == 12 ? UpcCode.new(@query) : @query).to_i if @query =~ /^\d+$/
  end

  def set_cco_user
    @cco_user = CrewCorner::User.find(params[:id], access_token: @cco_access_token)

    render_not_found if @cco_user.nil?
  end

  def person_params
    params.require(:person).permit(:administrator)
  end
end

app/controllers/people_controller.rb
require 'upc_code'

class PeopleController < ApplicationController
  before_filter :require_administrator_privileges
  before_filter :set_query, only: :search

  def index
    @current_user = CrewCorner::User.current(access_token: @cco_access_token)
  end

  def show
    @cco_user = CrewCorner::User.find(params[:id], access_token: @cco_access_token)
    @event_info = CrewCorner::EventInfo.find(params[:id], @current_event.cco_id, access_token: @cco_access_token)
    @person = Person.find_by_cco_id(params[:id])
  end

  def search
    case @query
    when Integer
      user = CrewCorner::User.find(@query, access_token: @cco_access_token)

      unless user.nil?
        redirect_to action: :show, id: @query
      else
        @users = []
      end
    when String
      @users = CrewCorner::User.search(@query, access_token: @cco_access_token)
    end
  end

  private

  def set_query
    @query = params[:q]
    @query = (@query.length == 12 ? UpcCode.new(@query) : @query).to_i if @query =~ /^\d+$/
  end
end

app/views/admin/people/index.html.erb
<h1>Folk</h1>

<section class="content">
  <p>Listan innehåller folk som har loggat in i Crewservicer.</p>

  <ul>
    <% @people.each do |person| %>
      <li>
          <a href="<%= admin_person_path(person) %>"><%= person.username %></a>
          <% if person.administrator? %>(Administratör)<% end %>
      </li>
    <% end %>
  </ul>
</section>

<% content_for :subnav do %>
  <%= render 'admin/system_subnav' %>
<% end %>

app/views/admin/people/search.html.erb
<form method="get" action="<%= search_admin_people_path %>">
	<input type="text" name="q" value="<%= params[:q] %>" />
	<input type="submit" value="Sök" />
</form>

<% unless @users.nil? %>
	<% if @users.empty? %>
		<p>Inga matchande personer hittades :(</p>
	<% else %>
		<ul>
			<% @users.each do |user| %>
				<li>
					<% if user.badge_picture %>
						<img src="<%= user.badge_picture_url(50, 50) %>" width="50" height="50" alt="<%= user.username %>">
					<% end %>
					<a href="<%= admin_person_path(user.uid) %>"><%= user.username %></a>
				</li>
			<% end %>
		</ul>
	<% end %>
<% end %>

app/views/admin/people/show.html.erb
<section class="content">
  <h1><%= @cco_user.username %></h1>

  <p><img src="<%= @cco_user.badge_picture_url(150, 150) %>" width="150" height="150" alt="<%= @cco_user.username %>"></p>

  <p><%= @cco_user.firstname %> <%= @cco_user.lastname %></p>
</section>

<section class="content">
  <h2>Eventinfo</h2>

  <% if @event_info.nil? %>
    <p><%= @cco_user.username %> har inte angivit eventinfo.</p>
  <% else %>
    <%= form_tag check_in_admin_person_path do %>
      <dl>
        <dt>Incheckad</dt>
        <dd>
          <% if @event_info.checkedin %>
            Ja, <%=l @event_info.checkedin_at, format: :short %> av <%= @event_info.checkedin_by %>
          <% else %>
            Nej <input type="submit" value="Checka in">
          <% end %>
        </dd>
      </dl>
    <% end %>
  <% end %>
</section>

<section class="content">
  <h2>Beställda t-shirts</h2>
  <% if @t_shirt_orders.size > 0 %>
    <ul>
      <% @t_shirt_orders.each do |order| %>
        <li>
          <%= order.model_text %> – <%= order.size_text %>
          <% if order.picked_up_at %>
            – Utlämnad <%=l order.picked_up_at, format: :short %>
          <% else %>
            <%= form_tag pick_up_t_shirt_admin_person_path do %>
              <%= hidden_field_tag :t_shirt_order_id, order.id %>
              <input type="submit" value="Lämna ut">
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p><em>Inga t-shirts valda i tid.</em></p>
  <% end %>
</section>

<section class="content">
  <h2>Crewservicer</h2>

  <%= form_for [ :admin, @person ], method: :put, url: admin_person_path(@cco_user.uid) do |f| %>
    <p><%= f.check_box :administrator %> Administratör</p>

    <% unless @person.persisted? %>
      <p><%= @cco_user.username %> har inte lags till i Crewservicer än.</p>
    <% end %>

    <p><input type="submit" value="<% if @person.persisted? %>Spara<% else %>Lägg till och spara<% end %>"></p>
  <% end %>
</section>