config/routes.rb
Crewservicer::Application.routes.draw do
  root to: 'dashboard#index', as: :dashboard

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login/redirect' => 'sessions#create', as: :oauth_redirect
  get 'login/callback' => 'sessions#callback', as: :oauth_callback

  get 'mat' => 'dashboard#food_services', as: :food_services
  get 'meddelanden' => 'dashboard#messages', as: :messages, constraints: { format: 'atom' }

  get 'slideshow' => 'dashboard#info_slideshow', as: :slideshow
  get 'slideshow/messages' => 'dashboard#slideshow_messages', as: :slideshow_messages, constraints: { format: 'json' }

  scope path_names: { :new => "ny", :edit => "redigera" } do
    namespace :admin do
      resources :people, only: [ :index, :show, :update ], path: 'folk' do
        member do
          post 'pick_up_t_shirt', path: 'hamta-t-shirt'
          post 'check_in', path: 'checka-in'
        end

        collection do
          get 'search', path: 'sok'
        end
      end

      resources :events, only: [ :index ], path: 'event' do
        collection do
          post 'import', path: 'importera'
        end
      end

      resources :food_services, except: [ :edit ], path: "maltider"

      resources :radio_orders, path: 'radiobestallningar' do
        member do
          get 'delivery_note', path: 'foljesedel'
          get 'equipment_pickup', path: 'lamna-ut'
          post 'pickup_equipment', path: 'lamna-ut'
          get 'equipment_return', path: 'lamna-tillbaka'
          post 'return_equipment', path: 'lamna-tillbaka'
        end

        resources :radio_loans, only: [ :show ], path: 'radios' do
          member do
            post 'bind_radio', path: 'koppla-radio'
          end
        end
      end

      resources :radios, only: [ :index ]

      resources :t_shirt_orders, only: [ :index ], path: 't-shirts'

      resources :messages, except: [ :edit ], path: "meddelanden" do
        collection do
          post 'sort', path: 'sortera'
        end

        member do
          post 'publish', path: 'publicera'
          post 'restore', path: 'aterstall'
        end
      end
    end
  end

  get '404' => 'errors#not_found'
  get '422' => 'errors#change_rejected'
  get '500' => 'errors#server_error'
end

app/models/radio_order.rb
class RadioOrder < ActiveRecord::Base
  belongs_to :event
  has_many :radio_loans

  accepts_nested_attributes_for :radio_loans, allow_destroy: true

  validates_presence_of :description, :pickup_time, :return_time, :remote_speakers,
                        :remote_speakers_picked_up, :earpieces, :earpieces_picked_up,
                        :headsets, :headsets_picked_up, :charging_stations,
                        :charging_stations_picked_up
  validate :return_after_pickup, :earpieces_not_exceeded, :remote_speakers_not_exceeded,
           :headsets_not_exceeded, :charging_stations_not_exceeded


  def earpieces_available
    earpieces - earpieces_picked_up
  end

  def remote_speakers_available
    remote_speakers - remote_speakers_picked_up
  end

  def headsets_available
    headsets - headsets_picked_up
  end

  def charging_stations_available
    charging_stations - charging_stations_picked_up
  end

  private

  def return_after_pickup
    if return_time.present? && pickup_time.present? && return_time < pickup_time
      errors.add(:return_time, :must_be_after_pickup)
    end
  end

  def earpieces_not_exceeded
    errors.add(:earpieces_picked_up, :must_not_exceed_available) if earpieces_available < 0
  end

  def remote_speakers_not_exceeded
    errors.add(:remote_speakers_picked_up, :must_not_exceed_available) if remote_speakers_available < 0
  end

  def headsets_not_exceeded
    errors.add(:headsets_picked_up, :must_not_exceed_available) if headsets_available < 0
  end

  def charging_stations_not_exceeded
    errors.add(:charging_stations_picked_up, :must_not_exceed_available) if charging_stations_available < 0
  end
end

app/controllers/admin/radio_orders_controller.rb
class Admin::RadioOrdersController < ApplicationController
  before_filter :require_administrator_privileges
  before_filter :set_radio_order, except: [ :index, :new, :create ]
  before_filter :set_pickup_radio_loans, only: :equipment_pickup
  before_filter :set_return_radio_loans, only: :equipment_return

  def index
    @radio_orders = @current_event.radio_orders.order('pickup_time ASC, description ASC')
    @radio_loan_counts = @current_event.radio_orders.includes(:radio_loans).references(:radio_loans).group('radio_orders.id').count('radio_loans.id')
    @prepared_radio_loan_counts = @current_event.radio_orders.includes(:radio_loans).references(:radio_loans)
      .where('radio_loans.radio_id IS NOT NULL').group('radio_orders.id').count('radio_loans.id')
    @picked_up_radio_loan_counts = @current_event.radio_orders.includes(:radio_loans).references(:radio_loans)
      .where('radio_loans.picked_up_at IS NOT NULL AND radio_loans.returned_at IS NULL').group('radio_orders.id').count('radio_loans.id')
  end

  def show
  end

  def new
    @radio_order = RadioOrder.new
  end

  def create
    @radio_order = RadioOrder.new(radio_order_params)
    @radio_order.event = @current_event

    if @radio_order.save
      redirect_to edit_admin_radio_order_path(@radio_order)
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @radio_order.update_attributes(radio_order_params)
      redirect_to edit_admin_radio_order_path(@radio_order)
    else
      render action: :edit
    end
  end

  def delivery_note
    render layout: false
  end

  def equipment_pickup
  end

  def equipment_return
  end

  def pickup_equipment
    @radio_order.earpieces_picked_up += params[:earpieces].to_i
    @radio_order.remote_speakers_picked_up += params[:remote_speakers].to_i
    @radio_order.headsets_picked_up += params[:headsets].to_i
    @radio_order.charging_stations_picked_up += params[:charging_stations].to_i

    unless @radio_order.save
      set_pickup_radio_loans
      render action: :equipment_pickup
      return
    end

    if params[:radio_loan_ids].present?
      RadioLoan.find(params[:radio_loan_ids]).each do |radio_loan|
        next if radio_loan.radio_order_id != @radio_order.id

        radio_loan.picked_up_at = Time.now
        radio_loan.save
      end
    end

    redirect_to admin_radio_order_path(@radio_order)
  end

  def return_equipment
    @radio_order.earpieces_picked_up -= params[:earpieces].to_i
    @radio_order.remote_speakers_picked_up -= params[:remote_speakers].to_i
    @radio_order.headsets_picked_up -= params[:headsets].to_i
    @radio_order.charging_stations_picked_up -= params[:charging_stations].to_i

    unless @radio_order.save
      set_return_radio_loans
      render action: :equipment_return
      return
    end

    if params[:radio_loan_ids].present?
      RadioLoan.find(params[:radio_loan_ids]).each do |radio_loan|
        next if radio_loan.radio_order_id != @radio_order.id

        radio_loan.returned_at = Time.now
        radio_loan.save
      end
    end

    redirect_to admin_radio_order_path(@radio_order)
  end

  private

  def set_radio_order
    @radio_order = RadioOrder.includes(:radio_loans => [ :radio ]).order('radio_loans.description').find(params[:id])
  end

  def set_pickup_radio_loans
    @prepared_radio_loans = @radio_order.radio_loans.where('radio_id IS NOT NULL AND picked_up_at IS NULL')
    @other_radio_loans = @radio_order.radio_loans.where('radio_id IS NULL OR (radio_id IS NOT NULL AND picked_up_at IS NOT NULL)')
  end

  def set_return_radio_loans
    @picked_up_radio_loans = @radio_order.radio_loans.where('picked_up_at IS NOT NULL AND returned_at IS NULL')
    @other_radio_loans = @radio_order.radio_loans.where('picked_up_at IS NULL OR (picked_up_at IS NOT NULL AND returned_at IS NOT NULL)')
  end

  def radio_order_params
    params.require(:radio_order).permit(
      :description,
      :pickup_time,
      :return_time,
      :remote_speakers,
      :earpieces,
      :headsets,
      :charging_stations,
      { radio_loans_attributes: [ :id, :_destroy, :description ] }
    )
  end
end

app/views/admin/radio_orders/_form.html.erb
<%= form_for [ :admin, @radio_order ] do |f| %>
  <% if @radio_order.errors.size > 0 %>
    <div class="errors">
      <span class="error-icon icon large">&#9888;</span>
      <p>Några fält måste korrigeras</p>
      <ul>
      <% @radio_order.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <label>
      <span class="label">Beskrivning</span>
      <%= f.text_field :description %>
    </label>
  </p>
  <p>
    <label>
      <span class="label">Upphämtning</span>
      <%= f.text_field :pickup_time, value: f.object.pickup_time %>
    </label>
  </p>
  <p>
    <label>
      <span class="label">Tillbakalämning</span>
      <%= f.text_field :return_time, value: f.object.return_time %>
    </label>
  </p>

  <h2>Tillbehör</h2>
  <table id="accessories">
    <thead>
      <tr>
        <th></th>
        <th>Antal</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Monofoner</td>
        <td class="full-field"><%= f.text_field :remote_speakers %></td>
      </tr>
      <tr>
        <td>Snäckor</td>
        <td class="full-field"><%= f.text_field :earpieces %></td>
      </tr>
      <tr>
        <td>Hörlurar</td>
        <td class="full-field"><%= f.text_field :headsets %></td>
      </tr>
      <tr>
        <td>Laddstationer</td>
        <td class="full-field"><%= f.text_field :charging_stations %></td>
      </tr>
    </tbody>
  </table>

  <h2>Radios</h2>
  <table id="radio-loans">
    <thead>
      <tr>
          <th>Beskrivning</th>
          <th></th>
      </tr>
    </thead>
    <tbody>
      <%= f.fields_for :radio_loans do |rf| %>
        <tr>
          <td class="full-field">
            <%= rf.text_field :description %>
          </td>
          <td>
            <%= rf.hidden_field :id %>
            <label class="button"><%= rf.check_box '_destroy', class: "destroy" %> Ta bort</label>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <p><a id="new-radio-loan" class="button" href="#">Lägg till</a></p>
  <p><input type="submit" value="Spara"> <a href="<%= admin_radio_orders_path %>">Tillbaka</a></p>
<% end %>

<% content_for :javascript_init do %>
  <script type="text/javascript">
    window.addEvent("domready", function() {
      new Form.NestedAttributesTable($("radio-loans"), $("new-radio-loan"), RadioOrders.NewRadioLoanRow, <%= @radio_order.radio_loans.size %>)
    })
  </script>
<% end %>

app/views/admin/radio_orders/delivery_note.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0">
    <title>Crewinfo</title>
    <%= stylesheet_link_tag "print", :media => "all" %>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" href="<%= image_path 'dreamhack-touch-icon.png' %>">
  </head>
  <body>
    <h1>Följesedel radiobeställning</h1>

    <dl>
      <dt>Beskrivning</dt>
      <dd><strong><%= @radio_order.description %></strong></dd>
      <dt>Hämtas upp</dt>
      <dd><strong><%=l @radio_order.pickup_time, format: :short %></strong></dd>
      <dt>Lämnas tillbaka senast</dt>
      <dd><strong><%=l @radio_order.return_time, format: :short %></strong></dd>
    </dl>

    <h2>Utrustning</h2>
    <table>
      <thead>
        <tr>
          <th>Enhet</th>
          <th>Benämning</th>
          <th>Serienummer</th>
          <th>Antal</th>
        </tr>
      </thead>
      <tbody>
        <% @radio_order.radio_loans.each do |radio_loan| %>
          <tr>
            <td>
              Radio
            </td>
            <td>
              <%= radio_loan.description %>
            </td>
            <td>
              <% if radio_loan.radio %>
                <%= radio_loan.radio.serial_number %>
              <% else %>
                –
              <% end %>
            </td>
            <td>1 st</td>
          </tr>
        <% end %>
        <% if @radio_order.remote_speakers > 0 %>
          <tr>
            <td>Monofon</td>
            <td></td>
            <td></td>
            <td><%= @radio_order.remote_speakers %> st</td>
          </tr>
        <% end %>
        <% if @radio_order.earpieces > 0 %>
          <tr>
            <td>Snäckor</td>
            <td></td>
            <td></td>
            <td><%= @radio_order.earpieces %> st</td>
          </tr>
        <% end %>
        <% if @radio_order.headsets > 0 %>
          <tr>
            <td>Hörlurar</td>
            <td></td>
            <td></td>
            <td><%= @radio_order.headsets %></td>
          </tr>
        <% end %>
        <% if @radio_order.charging_stations > 0 %>
          <tr>
            <td>Laddstationer</td>
            <td></td>
            <td></td>
            <td><%= @radio_order.charging_stations %> st</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </body>
</html>

app/views/admin/radio_orders/edit.html.erb
<h1>Redigera radiobeställning</h1>
<%= render 'form' %>

<% content_for :subnav do %>
  <%= render 'admin/radio_subnav' %>
<% end %>

app/views/admin/radio_orders/equipment_pickup.html.erb
<h1>Lämna ut radioutrustning</h1>
<section class="content">
  <p>Beskrivning: <%= @radio_order.description %></p>
  <p>Period: <%=l @radio_order.pickup_time, format: :short %> - <%=l @radio_order.return_time, format: :short %></p>

  <% if @radio_order.errors.size > 0 %>
    <div class="errors">
      <span class="error-icon icon large">&#9888;</span>
      <p>Några fält måste korrigeras</p>
      <ul>
        <% @radio_order.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_tag pickup_equipment_admin_radio_order_path(@radio_order) do |f| %>
    <h2>Förberedda radios</h2>
    <% if @prepared_radio_loans.any? %>
      <table id="radio-loans">
        <thead>
          <tr>
            <th></th>
            <th>Beskrivning</th>
            <th>Serienummer</th>
          </tr>
        </thead>
        <tbody>
          <% @prepared_radio_loans.each do |radio_loan| %>
            <tr>
              <td>
                <%= check_box_tag 'radio_loan_ids[]', radio_loan.id, false, class: 'select-row' %>
              </td>
              <td>
                <%= radio_loan.description %>
              </td>
              <td>
                <% if radio_loan.radio %>
                  <%= radio_loan.radio.serial_number %>
                <% else %>
                  –
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Inga radios tillgängliga för utlämning.</p>
    <% end %>

    <% if @other_radio_loans.any? %>
      <h2>Övriga radios</h2>
      <table id="radio-loans">
        <thead>
        <tr>
          <th>Beskrivning</th>
          <th>Status</th>
          <th>Serienummer</th>
        </tr>
        </thead>
        <tbody>
        <% @other_radio_loans.each do |radio_loan| %>
          <tr>
            <td>
              <%= radio_loan.description %>
            </td>
            <td>
              <% case radio_loan.status when :returned %>
                Tillbakalämnad <%=l radio_loan.returned_at, format: :short %>
              <% when :picked_up %>
                Utlämnad <%=l radio_loan.picked_up_at, format: :short %>
              <% when :prepared %>
                Förberedd
              <% when :new %>
                Ny
              <% end %>
            </td>
            <td>
              <% if radio_loan.radio %>
                <%= radio_loan.radio.serial_number %>
              <% else %>
                –
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>

    <h2>Tillbehör</h2>
    <table id="accessories">
      <thead>
        <tr>
          <th></th>
          <th>Tillgängliga</th>
          <th>Lämnas ut</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Monofoner</td>
          <td><%= @radio_order.remote_speakers_available %></td>
          <td class="full-field"><%= text_field_tag :remote_speakers, params[:remote_speakers] %></td>
        </tr>
        <tr>
          <td>Snäckor</td>
          <td><%= @radio_order.earpieces_available %></td>
          <td class="full-field"><%= text_field_tag :earpieces, params[:earpieces] %></td>
        </tr>
        <tr>
          <td>Hörlurar</td>
          <td><%= @radio_order.headsets_available %></td>
          <td class="full-field"><%= text_field_tag :headsets, params[:headsets] %></td>
        </tr>
        <tr>
          <td>Laddstationer</td>
          <td><%= @radio_order.charging_stations_available %></td>
          <td class="full-field"><%= text_field_tag :charging_stations, params[:charging_stations] %></td>
        </tr>
      </tbody>
    </table>

    <p>
      <input class="submit-button" type="submit" value="Lämna ut vald utrustning">
    </p>
  <% end %>
</section>

<% content_for :subnav do %>
  <%= render 'admin/radio_subnav' %>
<% end %>

app/views/admin/radio_orders/equipment_return.html.erb
<h1>Lämna tillbaka radioutrustning</h1>
<section class="content">
  <p>Beskrivning: <%= @radio_order.description %></p>
  <p>Period: <%=l @radio_order.pickup_time, format: :short %> - <%=l @radio_order.return_time, format: :short %></p>

  <% if @radio_order.errors.size > 0 %>
    <div class="errors">
      <span class="error-icon icon large">&#9888;</span>
      <p>Några fält måste korrigeras</p>
      <ul>
        <% @radio_order.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_tag return_equipment_admin_radio_order_path(@radio_order) do |f| %>
    <h2>Utlämnade radios</h2>
    <% if @picked_up_radio_loans.any? %>
      <table id="radio-loans">
        <thead>
          <tr>
            <th></th>
            <th>Beskrivning</th>
            <th>Serienummer</th>
          </tr>
        </thead>
        <tbody>
          <% @picked_up_radio_loans.each do |radio_loan| %>
            <tr>
              <td>
                <%= check_box_tag 'radio_loan_ids[]', radio_loan.id, false, class: 'select-row' %>
              </td>
              <td>
                <%= radio_loan.description %>
              </td>
              <td>
                <% if radio_loan.radio %>
                  <%= radio_loan.radio.serial_number %>
                <% else %>
                  –
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Inga radios utlämnade.</p>
    <% end %>

    <% if @other_radio_loans.any? %>
      <h2>Övriga radios</h2>
      <table id="radio-loans">
        <thead>
        <tr>
          <th>Beskrivning</th>
          <th>Status</th>
          <th>Serienummer</th>
        </tr>
        </thead>
        <tbody>
        <% @other_radio_loans.each do |radio_loan| %>
          <tr>
            <td>
              <%= radio_loan.description %>
            </td>
            <td>
              <% case radio_loan.status when :returned %>
                Tillbakalämnad <%=l radio_loan.returned_at, format: :short %>
              <% when :picked_up %>
                Utlämnad <%=l radio_loan.picked_up_at, format: :short %>
              <% when :prepared %>
                Förberedd
              <% when :new %>
                Ny
              <% end %>
            </td>
            <td>
              <% if radio_loan.radio %>
                <%= radio_loan.radio.serial_number %>
              <% else %>
                –
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>

    <h2>Tillbehör</h2>
    <table id="accessories">
      <thead>
        <tr>
          <th></th>
          <th>Utlämnade</th>
          <th>Lämnas tillbaka</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Monofoner</td>
          <td><%= @radio_order.remote_speakers_picked_up %></td>
          <td class="full-field"><%= text_field_tag :remote_speakers, params[:remote_speakers] %></td>
        </tr>
        <tr>
          <td>Snäckor</td>
          <td><%= @radio_order.earpieces_picked_up %></td>
          <td class="full-field"><%= text_field_tag :earpieces, params[:earpieces] %></td>
        </tr>
        <tr>
          <td>Hörlurar</td>
          <td><%= @radio_order.headsets_picked_up %></td>
          <td class="full-field"><%= text_field_tag :headsets, params[:headsets] %></td>
        </tr>
        <tr>
          <td>Laddstationer</td>
          <td><%= @radio_order.charging_stations_picked_up %></td>
          <td class="full-field"><%= text_field_tag :charging_stations, params[:charging_stations] %></td>
        </tr>
      </tbody>
    </table>

    <p>
      <input class="submit-button" type="submit" value="Lämna tillbaka vald utrustning">
    </p>
  <% end %>
</section>

<% content_for :subnav do %>
  <%= render 'admin/radio_subnav' %>
<% end %>

app/views/admin/radio_orders/index.html.erb
<h1>Radiobeställningar</h1>

<section class="content">
  <% if @radio_orders.size > 0 %>
    <table id="dishes">
      <thead>
        <tr>
          <th>Beskrivning</th>
          <th>Period</th>
          <th>Radios</th>
          <th><abbr title="Förberedda radios">Förb.</abbr></th>
          <th><abbr title="Utlämnade radios">Utl.</abbr></th>
          <th>Tillbehör</th>
        </tr>
      </thead>
      <tbody>
        <% @radio_orders.each do |radio_order| %>
          <tr>
            <td>
              <a href="<%= admin_radio_order_path(radio_order) %>"><%= radio_order.description %></a>
            </td>
            <td>
                <%=l radio_order.pickup_time, format: :short %> -<br>
                <%=l radio_order.return_time, format: :short %>
            </td>
            <td>
              <%= @radio_loan_counts[radio_order.id] || 0 %> st
            </td>
            <td>
              <%= @prepared_radio_loan_counts[radio_order.id] || 0 %> st
            </td>
            <td>
              <%= @picked_up_radio_loan_counts[radio_order.id] || 0 %> st
            </td>
            <td>
              <% if radio_order.remote_speakers > 0 %>
                Monofoner: <%= radio_order.remote_speakers %> st, <%= radio_order.remote_speakers_picked_up %> st utl.<br>
              <% end %>
              <% if radio_order.earpieces > 0 %>
                Öronsnäckor: <%= radio_order.earpieces %> st, <%= radio_order.earpieces_picked_up %> st utl.<br>
              <% end %>
              <% if radio_order.headsets > 0 %>
                Hörlurar: <%= radio_order.headsets %> st, <%= radio_order.headsets_picked_up %> st utl.<br>
              <% end %>
              <% if radio_order.charging_stations > 0 %>
                Laddstat.: <%= radio_order.charging_stations %> st, <%= radio_order.charging_stations_picked_up %> st utl.<br>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>Inga radiobeställningar inkomna för det här eventet.</p>
  <% end %>
  <p><a href="<%= new_admin_radio_order_path %>" class="button">Ny radiobeställning</a></p>
</section>

<% content_for :subnav do %>
  <%= render 'admin/radio_subnav' %>
<% end %>

app/views/admin/radio_orders/new.html.erb
<h1>Ny radiobeställning</h1>
<%= render 'form' %>

<% content_for :subnav do %>
  <%= render 'admin/radio_subnav' %>
<% end %>

app/views/admin/radio_orders/show.html.erb
<h1>Radiobeställning</h1>
<section class="content">
  <p>Beskrivning: <%= @radio_order.description %></p>
  <p>Period: <%=l @radio_order.pickup_time, format: :short %> - <%=l @radio_order.return_time, format: :short %></p>

  <h2>Radios</h2>
  <table id="radio-loans">
    <thead>
      <tr>
          <th>Beskrivning</th>
          <th>Status</th>
          <th>Serienummer</th>
          <th></th>
      </tr>
    </thead>
    <tbody>
      <% @radio_order.radio_loans.each do |radio_loan| %>
        <tr>
          <td>
            <%= radio_loan.description %>
          </td>
          <td>
            <% case radio_loan.status when :returned %>
              Tillbakalämnad <%=l radio_loan.returned_at, format: :short %>
            <% when :picked_up %>
              Utlämnad <%=l radio_loan.picked_up_at, format: :short %>
            <% when :prepared %>
              Förberedd
            <% when :new %>
              Ny
            <% end %>
          </td>
          <td>
            <% if radio_loan.radio %>
              <%= radio_loan.radio.serial_number %>
            <% else %>
              –
            <% end %>
          </td>
          <td>
            <a class="button" href="<%= admin_radio_order_radio_loan_path(@radio_order, radio_loan) %>">
              <% case radio_loan.status when :new %>
                Förbered
              <% else %>
                Visa
              <% end %>
            </a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2>Tillbehör</h2>
  <table id="accessories">
    <thead>
      <tr>
        <th></th>
        <th>Beställda</th>
        <th>Utlämnade</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Monofoner</td>
        <td><%= @radio_order.remote_speakers %></td>
        <td><%= @radio_order.remote_speakers_picked_up %></td>
      </tr>
      <tr>
        <td>Snäckor</td>
        <td><%= @radio_order.earpieces %></td>
        <td><%= @radio_order.earpieces_picked_up %></td>
      </tr>
      <tr>
        <td>Hörlurar</td>
        <td><%= @radio_order.headsets %></td>
        <td><%= @radio_order.headsets_picked_up %></td>
      </tr>
      <tr>
        <td>Laddstationer</td>
        <td><%= @radio_order.charging_stations %></td>
        <td><%= @radio_order.charging_stations_picked_up %></td>
      </tr>
    </tbody>
  </table>

  <p>
    <a class="button" href="<%= equipment_pickup_admin_radio_order_path(@radio_order) %>">
      Lämna ut utrustning
    </a>
    <a class="button" href="<%= equipment_return_admin_radio_order_path(@radio_order) %>">
      Lämna tillbaka utrustning
    </a>
    <a class="button" href="<%= delivery_note_admin_radio_order_path(@radio_order) %>">
      Skriv ut följesedel
    </a>
    <a class="button" href="<%= edit_admin_radio_order_path(@radio_order) %>">
      Redigera beställning
    </a>
  </p>
</section>

<% content_for :subnav do %>
  <%= render 'admin/radio_subnav' %>
<% end %>